### ISSUE TITLE
External Graphic dosn't work for line symbolizer

### ISSUE THREAD

**Issue by Meshkipoosh** [NieuwlandGeo/SLDReader#101]
Here is the style i want to use for a line feature:

       <LineSymbolizer>
            <Stroke>
              <CssParameter name="stroke">#000000</CssParameter>
              <CssParameter name="stroke-width">1.06</CssParameter>
            </Stroke>
          </LineSymbolizer>
          <PointSymbolizer>
            <Graphic>
              <ExternalGraphic>
                <OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADkAAAA2CAYAAAB9TjFQAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAOwAAADsABataJCQAABjpJREFUaEPNmf1Pk1cUx/kbFqMOQaAttPQNECYjmrhFpw4olA5BsxizJW7LsiU6BcpLQfD9B13Mkk2zqdPsr1uftz4vEH/67vuUVC09E2ifp+0PH3rP9x5+uL3nnnPubQuAfeOs3uGHPNeMiOKHcJ78CjX5CQrjEzRln2ZDFHdDG01BDYRQSF+gKfs0E6K4F9TJSSiBMIyJr2jKPs2CKO4VfWwCakcAxuQ0TdmnGRDF/aCNpaB1RWBmmjd0RXG/6ONpaIEeaBMZmrJPIxHFajCYbfNdAeiZ5gtdUawWfWIcSjeTUWaWpuzTCESxFvQUk1FXD4xU82RdUawVw62jnVzo1AxN2aeetGw+/wubDx5xLDtUi8FkpAYj0JugvPAcpaFHB+Bkl2nLTtVSXOjREEM3TVP2qQct5o8/8QyFoUX7YC2vUpMdq6UYuh1BmA3c0eIf8+r3UFq7oEaisNbWKcnO1VKso53dKExM0ZR9/OTtwJi+COVQG7RYH5z7jylVOteCG7oaW0CNreDOOb8pM/RTp6EdOAy9bxjWxl1K5c61YhTLC0O3zuWlzHAePYYai0M90M5k1Ad7fYNy+T/Uij45BeVoFwo8qzvn/KJCKFy+DLU9iPzBVmh9g9h6+JByuU+tuGdUbe+C8eU4TdnHSyqErRd/81wmkef5VNo7oMf7Ya7e5lS5X60YKXdH2evWIRmJop2ZgdraWcy2+bYg1J4EnA0/QjfDLzIE/Qt/d1QU3/zxFGqUZzPRj8KlK/wc5Fll1r1zj9OV/rVgpDLQ2jpgjPrXMIiii37iM6jdcbjha26sQwknoEVoL3lfR430FFRGjOFTeRFFF3P6EutaiDXzAU3aS6tQA2HooSjM+97vqM4zqjEZaefGaMo+1SKKLtbiKvRAN7Qz52hua+ZCluezF2o/k9EtH5LR+CSUNmbdsd2TkcVeu3DlWw7l+fcRxRJGvA9KV4TDd5q9vAathwmpJ47N1Vtlc15QcJMRI2i30C1Mz0Ib/BRvXr6iKfuUEMUS2tAwtI87OSzXnetzUEIM3d4E7Hvb4ewlblnR2gIwzo7SlH3M2a+hDY1g63mNi1RHTkA93M5h5Zy5uAStN8kW8DjrqPflxRhnMmJTUpiUW0DzylXog8Owf39Ks3L+fUSxhD5yEsrHHRzK83Y2B707Bj0ch7PmfejqaYZuZw/c992dc9bP19h6JlHY2D03iGKJwqkzLBsJDuV5F+vaL1xoBGpygKXG+x+CNNZR9WhnxRndvHsPurvT33xXpkuIYgkruwDz6g8cyvMl7OwSFH6r+cQxWLk1SrJftejj7gN2N8z0u9DdevGy2JUZp8+/1f4PUawGaz4LpTsKPcLOaN378uKeTY3XtFJ52Xr9D9T4ALT+waL9IUSxWswb8ywv7Iz6h3zpdY3UGHtd3kfZatosX/rZMXZlMVhsVHb6vo8o1oJbpPVYgreXJGw/QpflRWWLqZ85y0WOQu0IozB9kVOyv4so1oo9t8BuqZclpg+mDxdvg1lXDUehMQ8orKfa8EnKsq+LKHqBfX2h2NCr/ce4UO+zrpmeZtbl5f4w773skD6UZUXRK6zFZX7bCV7bkjBXvH/uNNMXislI+eggtOQgNv98RrnSr0LwGuvmAtQgG30u1PJhRwsXZqAc4QX/0BEUZuWzWSH4gTk/V9zRfxMDsFZ9eNfNXCouVAn0wJlfolQ+X2b4ib2cg+Je09gC+vJSn5nh+WyHERuA86D88a3M0W+suZvQglGokX7Yt71/19UnJpE/cIQt5iCcZ+/OZ4Wj35hLK+yKksUXQT9aQO18igtthX7qc5rbWoVTPbBWeHsJsKlnLbVyOUqyX7UU76PHR7D56jXNBi3Sxb6xWAxdJRaBefs+JdmvWpwnv/Fje1wxWU/s3DpraAwKz6jpQzIqIYr1xC6Gbhh6VxjWmvctoIso1htnfgFGKIq8m4x8eAUUxUbg5DZYWmLQeMOwsiuUZL9qEMVGYXNxejACJcg74h7ebvaKKDYSi3VUjbCpjyfg5LzZUVFsNObaGhsG3kdDvXB/ntg5v19EsRmw3GTEjJvnYs0aQ1cUm4XNbG77PsrLt3On+l5XFJsJO7sMIzkEJ1t5hdobaPkPnFdFrupy8W8AAAAASUVORK5CYII="/>
                <Format>image/png</Format>
              </ExternalGraphic>
              <Size>5</Size>
            </Graphic>
          </PointSymbolizer>

only the stroke is displayed and external graphic is ignored.

**Comment by ajkopinga** [comment]
Currently, SLDReader ignores PointSymbolizers for non-point geometries. According to the SLD specification, in these cases a point should be rendered in the 'middle' of the line/point geometry. I will fix this in the next SLDReader release.

**Comment by Meshkipoosh** [comment]
Thanks Arjen, When we can expect this release?
