### ISSUE TITLE
Faulty recursive function makes functionality break

### ISSUE THREAD

**Issue by z0zz0** [NieuwlandGeo/SLDReader#119]
### Our findings
Trying the latest release 0.2.14 for the new vendor options implemented completely breaks. We are certain to have found the reason for this. 

Looking at the function called **renderStrokeMarks** in _sldreader.js_, we can see that it is a recursive function that do not give itself all the parameters, specifically, the parameter called options is not given recursively (_sldreaderjs:2178_ and _sldreader.js:2195_). This renders "options" as undefined which causes an error further down in the code (_sldreader.js:2224_).

### Picture with comments on found faulty code
![image](https://user-images.githubusercontent.com/44770272/161232415-a13cd254-49dc-48a6-a6b8-b43efa2ddacd.png)

### Picture of where the error occurs
![image](https://user-images.githubusercontent.com/44770272/161232384-ff2e082a-22ef-4461-bd32-4710b927edf5.png)

### Picture of our fix (locally)
![image](https://user-images.githubusercontent.com/44770272/161232357-b0e40675-56a7-4ad9-a12a-a24b607c07c4.png)

**Cheers!**

**Comment by ajkopinga** [comment]
I have published v0.2.15 with this fix.
