### ISSUE TITLE
Fill and Stroke with color from PropertyName does not work

### ISSUE THREAD

**Issue by 1Map** [NieuwlandGeo/SLDReader#124]
<img width="604" alt="image" src="https://user-images.githubusercontent.com/1152458/169288986-3267b39a-39ba-4721-8a9e-f8f387f7bd0e.png">

<img width="515" alt="image" src="https://user-images.githubusercontent.com/1152458/169289087-f8970e22-5765-42fb-9d8b-c7d8e4943895.png">

**Comment by 1Map** [comment]
PLEASE NOTE: I carry my color value (hex value - for example: #000000) in a **property** and is not a **literal**.

**Comment by ajkopinga** [comment]
Dynamic styling parameters using `ogc:PropertyName` are now possible with the release of v0.3.0.
