### ISSUE TITLE
add an external graphic

### ISSUE THREAD

**Issue by mardani78** [NieuwlandGeo/SLDReader#131]
I wanna add an external graphic to my map but when I use my SLD, just shows a small square.
I would appreciate your help...
![Uploading externalgraphic.png…]()
<sld:Rule>       
		
          <PointSymbolizer>
                <Graphic>
                  <ExternalGraphic>
                    <OnlineResource
                    xlink:type="simple"
                    xlink:href="F:\r.mardani\office\IMIDRO_SLD\html\graphics\three.png"/>
                    <Format>image/png</Format>
                  </ExternalGraphic>
				  
                </Graphic>
          </PointSymbolizer>
          		  
          		  
        
		 </sld:Rule>

**Comment by ajkopinga** [comment]
The image link you're using points to an image on your local file system. This does not work, even when you run the web page on your own PC. You need to host the image somewhere online.
