### ISSUE TITLE
new kind of SLD

### ISSUE THREAD

**Issue by mardani78** [NieuwlandGeo/SLDReader#143]
![image](https://user-images.githubusercontent.com/114813009/217226890-8f1ac2d9-c358-4174-9014-1d5ae79540d3.png)

hi,
would you help me to have this kind of SLD?
color are watercolor and ways are not straight...

**Comment by ajkopinga** [comment]
This effect cannot be accomplished with an SLD in OpenLayers. What you see is probably a tiled service that uses pre-rendered tiles.
