### ISSUE TITLE
how to start a mark from the middle of the line

### ISSUE THREAD

**Issue by mardani78** [NieuwlandGeo/SLDReader#145]
![image](https://user-images.githubusercontent.com/114813009/227887820-c3af4025-95b1-4d34-ae3a-01685c4f80a2.png)
hi,
I don't want my Question mark and Square start from the beginning of the line so i can have this style:
![image](https://user-images.githubusercontent.com/114813009/227888228-efbd3b72-a27a-4b27-bf61-aa900b9c7865.png)

I'll appreciate your help..

**Comment by ajkopinga** [comment]
You can do this with the `InitialGap` property of a graphic stroke. I have just finished implementing this in v0.2.18 of the SLDReader library, along with some other changes that now enable you to cleanly overlay two different graphic strokes.

Check out the 'Alternating graphics' example [here](https://nieuwlandgeo.github.io/SLDReader/hoogspanning.html) .

Let me know if this works for you.

**Comment by mardani78** [comment]
> You can do this with the `InitialGap` property of a graphic stroke. I have just finished implementing this in v0.2.18 of the SLDReader library, along with some other changes that now enable you to cleanly overlay two different graphic strokes.
> 
> Check out the 'Alternating graphics' example [here](https://nieuwlandgeo.github.io/SLDReader/hoogspanning.html) .
> 
> Let me know if this works for you.





thank you so much...
it works very well and solved many problems.
