### ISSUE TITLE
Add TextSymbolizers

### ISSUE THREAD

**Issue by allartk** [NieuwlandGeo/SLDReader#18]
Add TextSymbolizers 

https://docs.geoserver.org/latest/en/user/styling/sld/reference/textsymbolizer.html

**Comment by allyoucanmap** [comment]
Hi @allartk I made a branch where a started to implement TextSymbolizers maybe it could be useful for the current issue:
https://github.com/allyoucanmap/SLDReader/tree/vt

diff:
https://github.com/NieuwlandGeo/SLDReader/compare/master...allyoucanmap:vt

In this branch you can find also
- stroke opacity (I just sent a PR for this commit)
https://github.com/NieuwlandGeo/SLDReader/commit/f75caae21ed2ebe9392ff5aefaf3057ff0b102a0
- an implementation to externalize icon data for `style.externalgraphic.onlineresource`
https://github.com/NieuwlandGeo/SLDReader/commit/4b07a4c687dbaf0e7d16e3a8d85ad74423cb217f
https://github.com/NieuwlandGeo/SLDReader/commit/f4acce096e7cb73143b3e190e7bb404228749037

- text symbolizer
https://github.com/NieuwlandGeo/SLDReader/commit/61bd4d9469137e60eddfab4cba8527a37f5008e5
https://github.com/NieuwlandGeo/SLDReader/commit/afebdd7e7fbb5b7116b22ea0974989e0734bf579
https://github.com/NieuwlandGeo/SLDReader/commit/fe922c7244c8c6f3d4457f4624b3ffb59ca5d719

**Comment by allartk** [comment]
Useful code indeed! We would welcome some (smaller) pull requests.

**Comment by allartk** [comment]
This is done :+1:
