### ISSUE TITLE
OLStyler stroke of polygon is visible around tiles when greater than tile buffer (tiled maps)

### ISSUE THREAD

**Issue by allyoucanmap** [NieuwlandGeo/SLDReader#27]
When stroke width is greater than tile buffer (or tile buffer is small) the tile grid is visible.
Current SLDReader implementation creates a polygon style from a single OL Style source and the stroke is applied on top of fill.
SLD uses as test case.
```xml
<UserStyle>
 <FeatureTypeStyle>
  <Rule>
   <PolygonSymbolizer>
    <Fill>
     <CssParameter name="fill">#acdd7a</CssParameter>
    </Fill>
    <Stroke>
     <CssParameter name="stroke">#333</CssParameter>
     <CssParameter name="stroke-width">50</CssParameter>
    </Stroke>
   </PolygonSymbolizer>
  </Rule>
 </FeatureTypeStyle>
</UserStyle>
```
Image below shows what happen when stroke is greater than tile buffer.

![actual_imp](https://user-images.githubusercontent.com/19175505/52483060-3f246180-2bb3-11e9-8080-bae03efc8b34.png)

A possible solution could be to split polyon style in an array that apply fill on top of stoke.
Here https://github.com/NieuwlandGeo/SLDReader/compare/master...allyoucanmap:polygon-stroke the code implemented to get the result you can see in the below image

![possible_soultion](https://user-images.githubusercontent.com/19175505/52483080-4e0b1400-2bb3-11e9-81f5-163c89690b21.png)

There are still two issues in the proposed solution:
- stroke-width needs to be multiply by 2 to be the right size when fill is rendered on top of it
- if fill is missing the issue is still there as in the following image

![without_fill](https://user-images.githubusercontent.com/19175505/52483122-654a0180-2bb3-11e9-925b-309e2d3f3076.png)

If this solution https://github.com/NieuwlandGeo/SLDReader/compare/master...allyoucanmap:polygon-stroke could work I can provide a PR.

**Comment by ajkopinga** [comment]
According to the SLD spec, stroke should always be rendered on top of the fill inside a single PolygonSymbolizer.

As a workaround, you can add two symbolizers inside a rule, a symbolizer with only a fill following a symbolizer with only a stroke.
