### ISSUE TITLE
Sizes in string

### ISSUE THREAD

**Issue by Razi91** [NieuwlandGeo/SLDReader#73]
Widths and sizes are parsed from XML as strings, then without casts, they are used in addictions. Those sizes should be parsed into float, before using in computing, like:
```js
  const radius = 0.5 * size;
```
to
```js
  const radius = 0.5 * parseFloat(size);
```

Same thing with `styleParams.strokeWidth` in `simpleStyles.js#28`

With that fix, it works fine. But any idea how it would work with issue #36?

**Comment by ajkopinga** [comment]
While I agree that it's nice to be explicit about when values are numeric, in your example above Javascript automatically converts size to a number when it's multiplied by a number.

Is this causing any bugs with a particular SLD?

I'm also not sure how this relates to issue #36.

**Comment by Razi91** [comment]
ok, I used wrong example. Another: `getSimpleStroke` returns param `width: styleParams.strokeWidth || 1,`. It's not parsed, therefore `width` might be string. This object is used to create style, and used for example in RegularShape: `var size = 2 * (this.radius_ + strokeWidth) + 1;`. We have `number * (number * string)`, result might be either wrong number (like `2 * (1 + "2") = 2 * "12") or NaN.

Tests are wrong:
```js
expect(featureStyle.getStroke().getWidth()).to.equal('4');
```
We are expecting this value to be string. Test will pass, but style won't render correctly in OL (or at all, if there will be two floating points value).

Probably they changed something in OpenLayers, dropping parsing to number, but I think docs never said strings are allowed there.

**Comment by ajkopinga** [comment]
That fix looks good to me. Can you make a pull request for it?

**Comment by Razi91** [comment]
Sure, let me just fix my repository,

**Comment by ajkopinga** [comment]
I've merged your fix. Thanks!
