### ISSUE TITLE
Refactor style reader

### ISSUE THREAD

**Issue by allartk** [NieuwlandGeo/SLDReader#76]
After some refactor of the filter: https://github.com/NieuwlandGeo/SLDReader/pull/63/files 

It might help to do the same for styles, as alternative for #73 and #74

**Comment by ajkopinga** [comment]
v0.3.0 has had a major refactoring of the SLD parser. Numeric expressions now get `typeHint: 'number'` to make sure they are treated as numbers after evaluating them.
