### ISSUE TITLE
Incorrect data in the example

### ISSUE THREAD

**Issue by Feofilakt** [NieuwlandGeo/SLDReader#82]
Hello! Found possible problem.

Reproduction:
1. Take xml data file from https://nieuwlandgeo.github.io/SLDReader/benelux.html
2. Take xml schema file from http://schemas.opengis.net/sld/1.0.0/StyledLayerDescriptor.xsd
3. Validate data with schema (for example, on https://www.liquid-technologies.com/online-xsd-validator)

There are validation errors, i.e. example data has wrong format.

**Comment by ajkopinga** [comment]
I have edited the example SLDs. They should now conform to the schema correspondong to their SLD version number.
