### ISSUE TITLE
Implementing AnchorPoint for TextSymbolizer PointPlacement

### ISSUE THREAD

**Issue by richard-thomas** [NieuwlandGeo/SLDReader#99]
Currently with TextSymbolizer in sldreader "For PointPlacement, AnchorPoint is not supported". Although the OpenLayers equivalent is limited to the much cruder TextBaseline and TextAlign properties, it would be very helpful (certainly in using SLD generated by QGIS) if some support for this could be added. The code below is one possible method (based on code I currently use to work around the issue), where olStyle is an input TextSymbolizer rule and ftsTextsymbolizer is the FeatureTypeStyle TextSymbolizer extracted from the SLD:

```
var olStyleText = olStyle.getText();
var anchor = ftsTextsymbolizer.labelplacement.pointplacement.anchorpoint;
var anchorX = anchor.anchorpointx;
var anchorY = anchor.anchorpointy;
if (anchorX < 0.25) {
    olStyleText.setTextAlign('left');
} else if (anchorX > 0.75) {
    olStyleText.setTextAlign('right');
} else {
    olStyleText.setTextAlign('center');
}
if (anchorY < 0.25) {
    olStyleText.setTextBaseline('bottom');
} else if (anchorY > 0.75) {
    olStyleText.setTextBaseline('top');
} else {
    olStyleText.setTextBaseline('middle');
}
```
Although this might seem a crude mapping, I believe that in most cases the text symbolizer anchor point (within the label) is likely to be either in the middle (0.5) or at one edge (0.0 or 1.0). With QGIS 3.18, this works well (in combination with displacementx / displacementy) for labelled point symbols that use "offset from point" label placement when position is set to right, bottom, or bottom right.

Unfortunately there seems to be a bug in QGIS that it (currently) will not write out negative displacement values for labels, so labels in other position (above/left) tend to get their displacement values discarded. However, if the QGIS-output SLD is modified to add the missing displacement values that were specified in QGIS label settings, then the above code combined with sldreader gives very good text placement for all label positions.

**Comment by ajkopinga** [comment]
I agree that this mapping, while crude, makes sense for most label placement use cases. I have implemented it and it will be part of the next SLDReader release.
